name: .NET Core Desktop

on:
  push:
    branches: [ "Release" ]
  pull_request:
    branches: [ "Release" ]

jobs:

  build:
    runs-on: windows-latest

    env:
      Solution_Name: Source\StaX.sln
      Configuration: Release
      Wap_Project_Directory: Publish
      Wap_Project_Path: Source\StaX.Desktop\StaX.Desktop.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish the application
      run: dotnet publish $env.Wap_Project_Path -p:PublishSingleFile=True --sc true -c $env.Configuration
      working-directory: Source/StaX.Desktop

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: StaX.Desktop
        path: $env.Wap_Project_Directory
